// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import { context } from "$live/live.ts";
import { DecoManifest } from "$live/types.ts";
import * as $0 from "./routes/[...catchall].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_500.tsx";
import * as $3 from "./routes/_app.tsx";
import * as $4 from "./routes/_middleware.ts";
import * as $5 from "./routes/api/[...catchall].tsx";
import * as $6 from "./routes/index.tsx";
import * as $$0 from "./islands/AddToCartButton.tsx";
import * as $$1 from "./islands/HeaderButton.tsx";
import * as $$2 from "./islands/HeaderModals.tsx";
import * as $$3 from "./islands/HeaderSearchMenu.tsx";
import * as $$4 from "./islands/Newsletter.tsx";
import * as $$5 from "./islands/ProductShelf.tsx";
import * as $$6 from "./islands/SearchControls.tsx";
import * as $$7 from "./islands/ShippingSimulation.tsx";
import * as $$8 from "./islands/SliderJS.tsx";
import * as $$$0 from "./sections/BannerGrid.tsx";
import * as $$$1 from "./sections/Carousel.tsx";
import * as $$$2 from "./sections/CookieConsent.tsx";
import * as $$$3 from "./sections/DesignSystem.story.tsx";
import * as $$$4 from "./sections/Features.tsx";
import * as $$$5 from "./sections/Footer.tsx";
import * as $$$6 from "./sections/Header.tsx";
import * as $$$7 from "./sections/Highlights.tsx";
import * as $$$8 from "./sections/ProductDescription.tsx";
import * as $$$9 from "./sections/ProductDetails.tsx";
import * as $$$10 from "./sections/ProductGallery.tsx";
import * as $$$11 from "./sections/ProductShelf.tsx";
import * as $$$12 from "./sections/ProductSpecTable.tsx";
import * as $$$13 from "./sections/ProductSpecification.tsx";
import * as $$$14 from "./sections/RichText.tsx";
import * as $$$15 from "./sections/SearchControls.tsx";
import * as $$$16 from "./sections/WhatsApp.tsx";
import * as $$$17 from "deco-sites/std/sections/SEO.tsx";
import * as $$$18 from "deco-sites/std/sections/SEOPDP.tsx";
import * as $$$19 from "deco-sites/std/sections/SEOPLP.tsx";
import * as $$$20 from "deco-sites/std/sections/configOCC.global.tsx";
import * as $$$21 from "deco-sites/std/sections/configShopify.global.tsx";
import * as $$$22 from "deco-sites/std/sections/configVTEX.global.tsx";
import * as $$$$0 from "./functions/mzVtexLegacyProductDetailsPage.ts";
import * as $$$$1 from "./functions/mzVtexLegacyProductList.ts";
import * as $$$$2 from "./functions/mzVtexLegacyProductListingPage.ts";
import * as $$$$3 from "$live/functions/EffectSelectPage.ts";
import * as $$$$4 from "$live/functions/MatchDate.ts";
import * as $$$$5 from "$live/functions/MatchEnvironment.ts";
import * as $$$$6 from "$live/functions/MatchRandom.ts";
import * as $$$$7 from "$live/functions/MatchSite.ts";
import * as $$$$8 from "$live/functions/MatchUserAgent.ts";
import * as $$$$9 from "deco-sites/std/functions/occProductDetailsPage.ts";
import * as $$$$10 from "deco-sites/std/functions/shopifyProductDetailsPage.ts";
import * as $$$$11 from "deco-sites/std/functions/shopifyProductList.ts";
import * as $$$$12 from "deco-sites/std/functions/shopifyProductListingPage.ts";
import * as $$$$13 from "deco-sites/std/functions/vtexConfig.ts";
import * as $$$$14 from "deco-sites/std/functions/vtexLegacyProductDetailsPage.ts";
import * as $$$$15 from "deco-sites/std/functions/vtexLegacyProductList.ts";
import * as $$$$16 from "deco-sites/std/functions/vtexLegacyProductListingPage.ts";
import * as $$$$17 from "deco-sites/std/functions/vtexProductDetailsPage.ts";
import * as $$$$18 from "deco-sites/std/functions/vtexProductList.ts";
import * as $$$$19 from "deco-sites/std/functions/vtexProductListingPage.ts";
import * as $$$$20 from "deco-sites/std/functions/vtexSuggestions.ts";

const manifest: DecoManifest = {
  routes: {
    "./routes/[...catchall].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_500.tsx": $2,
    "./routes/_app.tsx": $3,
    "./routes/_middleware.ts": $4,
    "./routes/api/[...catchall].tsx": $5,
    "./routes/index.tsx": $6,
  },
  islands: {
    "./islands/AddToCartButton.tsx": $$0,
    "./islands/HeaderButton.tsx": $$1,
    "./islands/HeaderModals.tsx": $$2,
    "./islands/HeaderSearchMenu.tsx": $$3,
    "./islands/Newsletter.tsx": $$4,
    "./islands/ProductShelf.tsx": $$5,
    "./islands/SearchControls.tsx": $$6,
    "./islands/ShippingSimulation.tsx": $$7,
    "./islands/SliderJS.tsx": $$8,
  },
  sections: {
    "./sections/BannerGrid.tsx": $$$0,
    "./sections/Carousel.tsx": $$$1,
    "./sections/CookieConsent.tsx": $$$2,
    "./sections/DesignSystem.story.tsx": $$$3,
    "./sections/Features.tsx": $$$4,
    "./sections/Footer.tsx": $$$5,
    "./sections/Header.tsx": $$$6,
    "./sections/Highlights.tsx": $$$7,
    "./sections/ProductDescription.tsx": $$$8,
    "./sections/ProductDetails.tsx": $$$9,
    "./sections/ProductGallery.tsx": $$$10,
    "./sections/ProductShelf.tsx": $$$11,
    "./sections/ProductSpecTable.tsx": $$$12,
    "./sections/ProductSpecification.tsx": $$$13,
    "./sections/RichText.tsx": $$$14,
    "./sections/SearchControls.tsx": $$$15,
    "./sections/WhatsApp.tsx": $$$16,
    "deco-sites/std/sections/SEO.tsx": $$$17,
    "deco-sites/std/sections/SEOPDP.tsx": $$$18,
    "deco-sites/std/sections/SEOPLP.tsx": $$$19,
    "deco-sites/std/sections/configOCC.global.tsx": $$$20,
    "deco-sites/std/sections/configShopify.global.tsx": $$$21,
    "deco-sites/std/sections/configVTEX.global.tsx": $$$22,
  },
  functions: {
    "./functions/mzVtexLegacyProductDetailsPage.ts": $$$$0,
    "./functions/mzVtexLegacyProductList.ts": $$$$1,
    "./functions/mzVtexLegacyProductListingPage.ts": $$$$2,
    "$live/functions/EffectSelectPage.ts": $$$$3,
    "$live/functions/MatchDate.ts": $$$$4,
    "$live/functions/MatchEnvironment.ts": $$$$5,
    "$live/functions/MatchRandom.ts": $$$$6,
    "$live/functions/MatchSite.ts": $$$$7,
    "$live/functions/MatchUserAgent.ts": $$$$8,
    "deco-sites/std/functions/occProductDetailsPage.ts": $$$$9,
    "deco-sites/std/functions/shopifyProductDetailsPage.ts": $$$$10,
    "deco-sites/std/functions/shopifyProductList.ts": $$$$11,
    "deco-sites/std/functions/shopifyProductListingPage.ts": $$$$12,
    "deco-sites/std/functions/vtexConfig.ts": $$$$13,
    "deco-sites/std/functions/vtexLegacyProductDetailsPage.ts": $$$$14,
    "deco-sites/std/functions/vtexLegacyProductList.ts": $$$$15,
    "deco-sites/std/functions/vtexLegacyProductListingPage.ts": $$$$16,
    "deco-sites/std/functions/vtexProductDetailsPage.ts": $$$$17,
    "deco-sites/std/functions/vtexProductList.ts": $$$$18,
    "deco-sites/std/functions/vtexProductListingPage.ts": $$$$19,
    "deco-sites/std/functions/vtexSuggestions.ts": $$$$20,
  },
  schemas: {
    "./sections/BannerGrid.tsx": {
      "inputSchema": {
        "title": " Banner Grid",
        "type": "object",
        "properties": {
          "title": {
            "type": [
              "string",
              "null",
            ],
            "title": "Title",
          },
          "itemsPerLine": {
            "title": "Items Per Line",
            "type": "object",
            "properties": {
              "mobile": {
                "type": [
                  "number",
                  "null",
                ],
                "title": "Mobile",
              },
              "desktop": {
                "type": [
                  "number",
                  "null",
                ],
                "title": "Desktop",
              },
            },
            "required": [],
            "description": "Default is 2 for mobile and all for desktop",
          },
          "borderRadius": {
            "title": "Border Radius",
            "type": "object",
            "properties": {
              "mobile": {
                "type": [
                  "number",
                  "null",
                ],
                "title": "Mobile",
              },
              "desktop": {
                "type": [
                  "number",
                  "null",
                ],
                "title": "Desktop",
              },
            },
            "required": [],
            "description": "Item's border radius in px",
          },
          "banners": {
            "type": "array",
            "items": {
              "title": "Banner",
              "type": "object",
              "properties": {
                "srcMobile": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Src Mobile",
                },
                "srcDesktop": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Src Desktop",
                },
                "alt": {
                  "type": "string",
                  "title": "Alt",
                  "description": "Image alt text",
                },
                "href": {
                  "type": "string",
                  "title": "Href",
                  "description": "When you click you go to",
                },
              },
              "required": [
                "srcMobile",
                "alt",
                "href",
              ],
            },
            "title": "Banners",
          },
        },
        "required": [
          "itemsPerLine",
          "borderRadius",
          "banners",
        ],
      },
      "outputSchema": null,
    },
    "./sections/Carousel.tsx": {
      "inputSchema": {
        "title": " Carousel",
        "type": "object",
        "properties": {
          "images": {
            "type": "array",
            "items": {
              "title": "Banner",
              "type": "object",
              "properties": {
                "desktop": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Desktop",
                  "description": "desktop otimized image",
                },
                "mobile": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Mobile",
                  "description": "mobile otimized image",
                },
                "alt": {
                  "type": "string",
                  "title": "Alt",
                  "description": "Image's alt text",
                },
                "action": {
                  "title": "Action",
                  "type": "object",
                  "properties": {
                    "href": {
                      "type": [
                        "string",
                        "null",
                      ],
                      "title": "Href",
                    },
                    "title": {
                      "type": [
                        "string",
                        "null",
                      ],
                      "title": "Title",
                    },
                    "subTitle": {
                      "type": [
                        "string",
                        "null",
                      ],
                      "title": "Sub Title",
                    },
                    "label": {
                      "type": [
                        "string",
                        "null",
                      ],
                      "title": "Label",
                    },
                  },
                  "required": [],
                },
              },
              "required": [
                "desktop",
                "mobile",
                "alt",
              ],
            },
            "title": "Images",
          },
          "preload": {
            "type": [
              "boolean",
              "null",
            ],
            "title": "Preload",
            "description":
              "Check this option when this banner is the biggest image on the screen for image optimizations",
          },
          "interval": {
            "type": [
              "number",
              "null",
            ],
            "title": "Autoplay interval",
            "description": "time (in seconds) to start the carousel autoplay",
          },
          "showNavigationArrows": {
            "type": "string",
            "anyOf": [
              {
                "type": "string",
                "const": "mobileOnly",
              },
              {
                "type": "string",
                "const": "desktopOnly",
              },
              {
                "type": "string",
                "const": "always",
              },
              {
                "type": "string",
                "const": "never",
              },
            ],
            "title": "Show Navigation Arrows",
            "description": "When navigation arrows should be rendered.",
          },
          "showPaginationDots": {
            "type": "string",
            "anyOf": [
              {
                "type": "string",
                "const": "mobileOnly",
              },
              {
                "type": "string",
                "const": "desktopOnly",
              },
              {
                "type": "string",
                "const": "always",
              },
              {
                "type": "string",
                "const": "never",
              },
            ],
            "title": "Show Pagination Dots",
            "description": "When pagination dots should be rendered.",
          },
          "showProgressiveDots": {
            "type": [
              "boolean",
              "null",
            ],
            "title": "Show Progressive Dots",
            "description":
              "Show dots with progressive status about current timeout.",
          },
        },
        "required": [],
      },
      "outputSchema": null,
    },
    "./sections/CookieConsent.tsx": {
      "inputSchema": null,
      "outputSchema": null,
    },
    "./sections/DesignSystem.story.tsx": {
      "inputSchema": null,
      "outputSchema": null,
    },
    "./sections/Features.tsx": {
      "inputSchema": {
        "title": " Features",
        "type": "object",
        "properties": {
          "features": {
            "type": "array",
            "items": {
              "title": "Feature",
              "type": "object",
              "properties": {
                "icon": {
                  "type": "string",
                  "anyOf": [
                    {
                      "type": "string",
                      "const": "ChevronLeft",
                    },
                    {
                      "type": "string",
                      "const": "ChevronRight",
                    },
                    {
                      "type": "string",
                      "const": "ChevronUp",
                    },
                    {
                      "type": "string",
                      "const": "ChevronDown",
                    },
                    {
                      "type": "string",
                      "const": "QuestionMarkCircle",
                    },
                    {
                      "type": "string",
                      "const": "User",
                    },
                    {
                      "type": "string",
                      "const": "ShoppingCart",
                    },
                    {
                      "type": "string",
                      "const": "Bars3",
                    },
                    {
                      "type": "string",
                      "const": "Heart",
                    },
                    {
                      "type": "string",
                      "const": "MagnifyingGlass",
                    },
                    {
                      "type": "string",
                      "const": "XMark",
                    },
                    {
                      "type": "string",
                      "const": "Plus",
                    },
                    {
                      "type": "string",
                      "const": "Minus",
                    },
                    {
                      "type": "string",
                      "const": "MapPin",
                    },
                    {
                      "type": "string",
                      "const": "Phone",
                    },
                    {
                      "type": "string",
                      "const": "Logo",
                    },
                    {
                      "type": "string",
                      "const": "Facebook",
                    },
                    {
                      "type": "string",
                      "const": "Instagram",
                    },
                    {
                      "type": "string",
                      "const": "Tiktok",
                    },
                    {
                      "type": "string",
                      "const": "Truck",
                    },
                    {
                      "type": "string",
                      "const": "TruckPDP",
                    },
                    {
                      "type": "string",
                      "const": "Discount",
                    },
                    {
                      "type": "string",
                      "const": "Return",
                    },
                    {
                      "type": "string",
                      "const": "CreditCard",
                    },
                    {
                      "type": "string",
                      "const": "Deco",
                    },
                    {
                      "type": "string",
                      "const": "Discord",
                    },
                    {
                      "type": "string",
                      "const": "Trash",
                    },
                    {
                      "type": "string",
                      "const": "FilterList",
                    },
                    {
                      "type": "string",
                      "const": "WhatsApp",
                    },
                    {
                      "type": "string",
                      "const": "NotFound",
                    },
                    {
                      "type": "string",
                      "const": "Mail",
                    },
                    {
                      "type": "string",
                      "const": "DoubleRightArrow",
                    },
                    {
                      "type": "string",
                      "const": "RightArrow",
                    },
                    {
                      "type": "string",
                      "const": "InstagramHeader",
                    },
                    {
                      "type": "string",
                      "const": "FacebookHeader",
                    },
                    {
                      "type": "string",
                      "const": "WhatsappHeader",
                    },
                    {
                      "type": "string",
                      "const": "MyStores",
                    },
                    {
                      "type": "string",
                      "const": "Wishlist",
                    },
                    {
                      "type": "string",
                      "const": "HeartFooter",
                    },
                    {
                      "type": "string",
                      "const": "PhoneFooter",
                    },
                    {
                      "type": "string",
                      "const": "WhatsappFooter",
                    },
                    {
                      "type": "string",
                      "const": "MailFooter",
                    },
                    {
                      "type": "string",
                      "const": "Pix",
                    },
                    {
                      "type": "string",
                      "const": "Visa",
                    },
                    {
                      "type": "string",
                      "const": "Mastercard",
                    },
                    {
                      "type": "string",
                      "const": "DinersClub",
                    },
                    {
                      "type": "string",
                      "const": "Elo",
                    },
                    {
                      "type": "string",
                      "const": "AmericanExpress",
                    },
                  ],
                  "title": "Icon",
                  "description": "Image src",
                },
                "title": {
                  "type": "string",
                  "title": "Title",
                  "description": "Title",
                },
                "description": {
                  "type": "string",
                  "title": "Description",
                  "description": "Description and Image alt text",
                },
              },
              "required": [
                "icon",
                "title",
                "description",
              ],
            },
            "title": "Features",
          },
        },
        "required": [
          "features",
        ],
      },
      "outputSchema": null,
    },
    "./sections/Footer.tsx": {
      "inputSchema": {
        "title": " Footer",
        "type": "object",
        "properties": {
          "paymentSystem": {
            "title": "Formas de Pagamento",
            "type": "object",
            "properties": {
              "label": {
                "type": [
                  "string",
                  "null",
                ],
                "title": "Título",
                "default": "Formas de Pagamento",
              },
              "icons": {
                "type": "array",
                "items": {
                  "title": "PaymentSystemsIconProps",
                  "type": "object",
                  "properties": {
                    "icon": {
                      "type": "string",
                      "anyOf": [
                        {
                          "type": "string",
                          "const": "Visa",
                        },
                        {
                          "type": "string",
                          "const": "Mastercard",
                        },
                        {
                          "type": "string",
                          "const": "DinersClub",
                        },
                        {
                          "type": "string",
                          "const": "Elo",
                        },
                        {
                          "type": "string",
                          "const": "AmericanExpress",
                        },
                      ],
                      "title": "Ícone",
                    },
                    "width": {
                      "type": [
                        "string",
                        "null",
                      ],
                      "title": "Largura",
                    },
                    "height": {
                      "type": [
                        "string",
                        "null",
                      ],
                      "title": "Altura",
                    },
                  },
                  "required": [],
                },
                "title": "Ícones",
              },
            },
            "required": [],
          },
          "securitySystem": {
            "title": "Selos de Segurança",
            "type": "object",
            "properties": {
              "label": {
                "type": [
                  "string",
                  "null",
                ],
                "title": "Título",
                "default": "Selos de Segurança",
              },
              "images": {
                "type": "array",
                "items": {
                  "title": "SecuritySystemImage",
                  "type": "object",
                  "properties": {
                    "src": {
                      "format": "image-uri",
                      "type": "string",
                      "title": "Imagem",
                    },
                    "href": {
                      "type": [
                        "string",
                        "null",
                      ],
                      "title": "URL do link da imagem",
                    },
                    "alt": {
                      "type": [
                        "string",
                        "null",
                      ],
                      "title": 'Propriedade "alt" da imagem',
                    },
                    "maxWidth": {
                      "type": [
                        "string",
                        "null",
                      ],
                      "title": "Largura máxima da imagem",
                    },
                    "width": {
                      "type": [
                        "string",
                        "null",
                      ],
                      "title": "Largura da imagem",
                    },
                    "height": {
                      "type": [
                        "string",
                        "null",
                      ],
                      "title": "Altura da imagem",
                    },
                  },
                  "required": [
                    "src",
                  ],
                },
                "title": "Imagens",
              },
            },
            "required": [],
          },
          "socialNetwork": {
            "title": "Redes Sociais",
            "type": "object",
            "properties": {
              "label": {
                "type": [
                  "string",
                  "null",
                ],
                "title": "Título",
                "default": "Redes Sociais",
              },
              "icons": {
                "type": "array",
                "items": {
                  "title": "SocialNetworkIconProps",
                  "type": "object",
                  "properties": {
                    "icon": {
                      "type": "string",
                      "anyOf": [
                        {
                          "type": "string",
                          "const": "Facebook",
                        },
                        {
                          "type": "string",
                          "const": "Instagram",
                        },
                      ],
                      "title": "Ícone da Rede Social",
                    },
                    "href": {
                      "type": [
                        "string",
                        "null",
                      ],
                      "title": "URLda Rede Social",
                    },
                    "alt": {
                      "type": [
                        "string",
                        "null",
                      ],
                      "title": 'Propriedade "alt" da imagem',
                    },
                  },
                  "required": [],
                },
                "title": "Ícones",
              },
            },
            "required": [],
          },
          "copyright": {
            "format": "html",
            "type": "string",
            "title": "Copyright",
          },
          "sections": {
            "type": "array",
            "items": {
              "title": "Section",
              "type": "object",
              "properties": {
                "label": {
                  "type": [
                    "string",
                    "null",
                  ],
                  "title": "Título",
                },
                "children": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "anyOf": [
                      {
                        "title": "StringItem",
                        "type": "object",
                        "properties": {
                          "label": {
                            "type": [
                              "string",
                              "null",
                            ],
                            "title": "Label",
                          },
                          "href": {
                            "type": [
                              "string",
                              "null",
                            ],
                            "title": "Href",
                          },
                        },
                        "required": [],
                      },
                      {
                        "title": "IconItem",
                        "type": "object",
                        "properties": {
                          "label": {
                            "format": "html",
                            "type": "string",
                            "title": "Label",
                          },
                          "href": {
                            "type": [
                              "string",
                              "null",
                            ],
                            "title": "Href",
                          },
                          "icon": {
                            "type": "string",
                            "anyOf": [
                              {
                                "type": "string",
                                "const": "ChevronLeft",
                              },
                              {
                                "type": "string",
                                "const": "ChevronRight",
                              },
                              {
                                "type": "string",
                                "const": "ChevronUp",
                              },
                              {
                                "type": "string",
                                "const": "ChevronDown",
                              },
                              {
                                "type": "string",
                                "const": "QuestionMarkCircle",
                              },
                              {
                                "type": "string",
                                "const": "User",
                              },
                              {
                                "type": "string",
                                "const": "ShoppingCart",
                              },
                              {
                                "type": "string",
                                "const": "Bars3",
                              },
                              {
                                "type": "string",
                                "const": "Heart",
                              },
                              {
                                "type": "string",
                                "const": "MagnifyingGlass",
                              },
                              {
                                "type": "string",
                                "const": "XMark",
                              },
                              {
                                "type": "string",
                                "const": "Plus",
                              },
                              {
                                "type": "string",
                                "const": "Minus",
                              },
                              {
                                "type": "string",
                                "const": "MapPin",
                              },
                              {
                                "type": "string",
                                "const": "Phone",
                              },
                              {
                                "type": "string",
                                "const": "Logo",
                              },
                              {
                                "type": "string",
                                "const": "Facebook",
                              },
                              {
                                "type": "string",
                                "const": "Instagram",
                              },
                              {
                                "type": "string",
                                "const": "Tiktok",
                              },
                              {
                                "type": "string",
                                "const": "Truck",
                              },
                              {
                                "type": "string",
                                "const": "TruckPDP",
                              },
                              {
                                "type": "string",
                                "const": "Discount",
                              },
                              {
                                "type": "string",
                                "const": "Return",
                              },
                              {
                                "type": "string",
                                "const": "CreditCard",
                              },
                              {
                                "type": "string",
                                "const": "Deco",
                              },
                              {
                                "type": "string",
                                "const": "Discord",
                              },
                              {
                                "type": "string",
                                "const": "Trash",
                              },
                              {
                                "type": "string",
                                "const": "FilterList",
                              },
                              {
                                "type": "string",
                                "const": "WhatsApp",
                              },
                              {
                                "type": "string",
                                "const": "NotFound",
                              },
                              {
                                "type": "string",
                                "const": "Mail",
                              },
                              {
                                "type": "string",
                                "const": "DoubleRightArrow",
                              },
                              {
                                "type": "string",
                                "const": "RightArrow",
                              },
                              {
                                "type": "string",
                                "const": "InstagramHeader",
                              },
                              {
                                "type": "string",
                                "const": "FacebookHeader",
                              },
                              {
                                "type": "string",
                                "const": "WhatsappHeader",
                              },
                              {
                                "type": "string",
                                "const": "MyStores",
                              },
                              {
                                "type": "string",
                                "const": "Wishlist",
                              },
                              {
                                "type": "string",
                                "const": "HeartFooter",
                              },
                              {
                                "type": "string",
                                "const": "PhoneFooter",
                              },
                              {
                                "type": "string",
                                "const": "WhatsappFooter",
                              },
                              {
                                "type": "string",
                                "const": "MailFooter",
                              },
                              {
                                "type": "string",
                                "const": "Pix",
                              },
                              {
                                "type": "string",
                                "const": "Visa",
                              },
                              {
                                "type": "string",
                                "const": "Mastercard",
                              },
                              {
                                "type": "string",
                                "const": "DinersClub",
                              },
                              {
                                "type": "string",
                                "const": "Elo",
                              },
                              {
                                "type": "string",
                                "const": "AmericanExpress",
                              },
                            ],
                            "title": "Icon",
                          },
                        },
                        "required": [],
                      },
                      {
                        "title": "AdvancedItem",
                        "type": "object",
                        "properties": {
                          "text": {
                            "format": "html",
                            "type": "string",
                            "title": "Text",
                          },
                        },
                        "required": [],
                      },
                    ],
                    "title": "Item",
                  },
                  "title": "Children",
                },
                "showPaymentSystems": {
                  "type": [
                    "boolean",
                    "null",
                  ],
                  "title": "Mostrar formas de pagamento?",
                },
                "showSecuritySystems": {
                  "type": [
                    "boolean",
                    "null",
                  ],
                  "title": "Mostrar selos de segurança?",
                },
                "showSocialNetworks": {
                  "type": [
                    "boolean",
                    "null",
                  ],
                  "title": "Mostrar redes sociais?",
                },
                "showGrid": {
                  "type": [
                    "boolean",
                    "null",
                  ],
                  "title": "Mostrar o menu em 2 colunas?",
                },
              },
              "required": [
                "children",
              ],
            },
            "title": "Seções",
          },
        },
        "required": [],
      },
      "outputSchema": null,
    },
    "./sections/Header.tsx": {
      "inputSchema": {
        "title": " Header",
        "type": "object",
        "properties": {
          "alert": {
            "title": "Alerts",
            "type": "object",
            "properties": {
              "links": {
                "type": "array",
                "items": {
                  "title": "IconLink",
                  "type": "object",
                  "properties": {
                    "icon": {
                      "type": "string",
                      "anyOf": [
                        {
                          "type": "string",
                          "const": "FacebookHeader",
                        },
                        {
                          "type": "string",
                          "const": "InstagramHeader",
                        },
                        {
                          "type": "string",
                          "const": "WhatsappHeader",
                        },
                        {
                          "type": "string",
                          "const": "MyStores",
                        },
                      ],
                      "title": "Icon",
                    },
                    "link": {
                      "type": [
                        "string",
                        "null",
                      ],
                      "title": "Link",
                    },
                  },
                  "required": [],
                },
                "title": "Links",
              },
              "alert": {
                "type": [
                  "string",
                  "null",
                ],
                "title": "Alert",
              },
              "storelink": {
                "type": "array",
                "items": {
                  "title": "IconLink",
                  "type": "object",
                  "properties": {
                    "icon": {
                      "type": "string",
                      "anyOf": [
                        {
                          "type": "string",
                          "const": "FacebookHeader",
                        },
                        {
                          "type": "string",
                          "const": "InstagramHeader",
                        },
                        {
                          "type": "string",
                          "const": "WhatsappHeader",
                        },
                        {
                          "type": "string",
                          "const": "MyStores",
                        },
                      ],
                      "title": "Icon",
                    },
                    "link": {
                      "type": [
                        "string",
                        "null",
                      ],
                      "title": "Link",
                    },
                  },
                  "required": [],
                },
                "title": "Storelink",
              },
              "alertStore": {
                "type": [
                  "string",
                  "null",
                ],
                "title": "Alert Store",
              },
            },
            "required": [],
          },
          "searchbar": {
            "title": "Search Bar",
            "type": "object",
            "properties": {
              "placeholder": {
                "type": [
                  "string",
                  "null",
                ],
                "title": "Placeholder",
                "description": "Search bar default placeholder message",
                "default": "What are you looking for?",
              },
              "action": {
                "type": [
                  "string",
                  "null",
                ],
                "title": "Page path",
                "description":
                  "When user clicks on the search button, navigate it to",
                "default": "/s",
              },
              "name": {
                "type": [
                  "string",
                  "null",
                ],
                "title": "Term name",
                "description":
                  "Querystring param used when navigating the user",
                "default": "q",
              },
              "query": {
                "type": [
                  "string",
                  "null",
                ],
                "title": "Query",
              },
            },
            "required": [],
          },
          "navItems": {
            "type": "array",
            "items": {
              "title": "NavItem",
              "type": "object",
              "properties": {
                "label": {
                  "type": "string",
                  "title": "Label",
                },
                "href": {
                  "type": "string",
                  "title": "Href",
                },
                "highlight": {
                  "type": [
                    "boolean",
                    "null",
                  ],
                  "title": "Highlight",
                },
                "children": {
                  "title": "Children",
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "label": {
                        "type": "string",
                        "title": "Label",
                      },
                      "href": {
                        "type": "string",
                        "title": "Href",
                      },
                      "children": {
                        "title": "Children",
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "label": {
                              "type": "string",
                              "title": "Label",
                            },
                            "href": {
                              "type": "string",
                              "title": "Href",
                            },
                          },
                          "required": [
                            "label",
                            "href",
                          ],
                        },
                      },
                    },
                    "required": [
                      "label",
                      "href",
                    ],
                  },
                },
                "image": {
                  "title": "Image",
                  "type": "object",
                  "properties": {
                    "src": {
                      "format": "image-uri",
                      "type": "string",
                      "title": "Src",
                    },
                    "alt": {
                      "type": [
                        "string",
                        "null",
                      ],
                      "title": "Alt",
                    },
                    "width": {
                      "type": [
                        "number",
                        "null",
                      ],
                      "title": "Width",
                    },
                    "height": {
                      "type": [
                        "number",
                        "null",
                      ],
                      "title": "Height",
                    },
                  },
                  "required": [],
                },
              },
              "required": [
                "label",
                "href",
              ],
            },
            "title": "Navigation items",
            "description":
              "Navigation items used both on mobile and desktop menus",
          },
          "products": {
            "$id": "1f15a836acd2ecbefef6eaf34ebcff98e39811f3",
            "format": "live-function",
            "type": "string",
            "title": "Product suggestions",
            "description": "Product suggestions displayed on search",
          },
          "suggestions": {
            "$id": "664f9b3b60b4a75294c340d8218b4ad76821fd58",
            "format": "live-function",
            "type": "string",
            "title": "Enable Top Search terms",
          },
          "configVTEX": {
            "$id": "4a94f4ff0e8e4441f26651aaed22f0df82f38c93",
            "format": "live-function",
            "type": "string",
            "title": "Config V T E X",
            "description": "vtex config used for search autocompletion;",
          },
        },
        "required": [],
      },
      "outputSchema": null,
    },
    "./sections/Highlights.tsx": {
      "inputSchema": {
        "title": " Highlights",
        "type": "object",
        "properties": {
          "highlights": {
            "type": "array",
            "items": {
              "title": "Highlight",
              "type": "object",
              "properties": {
                "src": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Src",
                },
                "alt": {
                  "type": "string",
                  "title": "Alt",
                },
                "href": {
                  "type": "string",
                  "title": "Href",
                },
                "label": {
                  "type": "string",
                  "title": "Label",
                },
              },
              "required": [
                "src",
                "alt",
                "href",
                "label",
              ],
            },
            "title": "Highlights",
          },
          "title": {
            "type": "string",
            "title": "Title",
          },
        },
        "required": [
          "title",
        ],
      },
      "outputSchema": null,
    },
    "./sections/ProductDescription.tsx": {
      "inputSchema": {
        "title": " Product Description",
        "type": "object",
        "properties": {
          "page": {
            "$id": "78c64adae4b16df19c6019918cf3380bc0a3ea85",
            "format": "live-function",
            "type": "string",
            "title": "Page",
          },
        },
        "required": [
          "page",
        ],
      },
      "outputSchema": null,
    },
    "./sections/ProductDetails.tsx": {
      "inputSchema": {
        "title": " Product Details",
        "type": "object",
        "properties": {
          "page": {
            "$id": "78c64adae4b16df19c6019918cf3380bc0a3ea85",
            "format": "live-function",
            "type": "string",
            "title": "Page",
          },
        },
        "required": [
          "page",
        ],
      },
      "outputSchema": null,
    },
    "./sections/ProductGallery.tsx": {
      "inputSchema": {
        "title": " Product Gallery",
        "type": "object",
        "properties": {
          "page": {
            "$id": "9ba29fcac079080c6f7cf16f40f91cf15a25d53f",
            "format": "live-function",
            "type": "string",
            "title": "Page",
          },
          "showFilters": {
            "type": [
              "boolean",
              "null",
            ],
            "title": "Mostrar a barra lateral de filtros?",
            "default": "true",
          },
        },
        "required": [
          "page",
        ],
      },
      "outputSchema": null,
    },
    "./sections/ProductShelf.tsx": {
      "inputSchema": {
        "title": " Product Shelf",
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "title": "Title",
          },
          "products": {
            "$id": "21e924ba7ad9b59dcefae01b9b38a3fb983875f0",
            "format": "live-function",
            "type": "string",
            "title": "Products",
          },
          "viewMoreLink": {
            "type": [
              "string",
              "null",
            ],
            "title": "View More Link",
          },
          "viewMoreText": {
            "type": [
              "string",
              "null",
            ],
            "title": "View More Text",
          },
        },
        "required": [
          "title",
          "products",
        ],
      },
      "outputSchema": null,
    },
    "./sections/ProductSpecTable.tsx": {
      "inputSchema": {
        "title": " Product Spec Table",
        "type": "object",
        "properties": {
          "title": {
            "type": [
              "string",
              "null",
            ],
            "title": "Título",
          },
          "page": {
            "$id": "78c64adae4b16df19c6019918cf3380bc0a3ea85",
            "format": "live-function",
            "type": "string",
            "title": "Page",
          },
        },
        "required": [
          "page",
        ],
      },
      "outputSchema": null,
    },
    "./sections/ProductSpecification.tsx": {
      "inputSchema": {
        "title": " Product Specification",
        "type": "object",
        "properties": {
          "specificationName": {
            "type": [
              "string",
              "null",
            ],
            "title": "Nome da Especificação",
          },
          "page": {
            "$id": "78c64adae4b16df19c6019918cf3380bc0a3ea85",
            "format": "live-function",
            "type": "string",
            "title": "Page",
          },
        },
        "required": [
          "page",
        ],
      },
      "outputSchema": null,
    },
    "./sections/RichText.tsx": {
      "inputSchema": {
        "title": " Rich Text",
        "type": "object",
        "properties": {
          "text": {
            "type": [
              "string",
              "null",
            ],
            "title": "Texto",
            "description":
              "Texto em linguagem Markdown a ser mostrado (confira o seguinte guia caso tenha dúvidas de como funciona o Markdown: https://www.markdownguide.org/cheat-sheet/)",
          },
        },
        "required": [],
      },
      "outputSchema": null,
    },
    "./sections/SearchControls.tsx": {
      "inputSchema": {
        "title": " Search Controls",
        "type": "object",
        "properties": {
          "page": {
            "$id": "9ba29fcac079080c6f7cf16f40f91cf15a25d53f",
            "format": "live-function",
            "type": "string",
            "title": "Page",
          },
          "layout": {
            "type": "string",
            "anyOf": [
              {
                "type": "string",
                "const": "responsive",
              },
              {
                "type": "string",
                "const": "desktop",
              },
              {
                "type": "string",
                "const": "mobile",
              },
            ],
            "title": "Layout",
            "default": "responsive",
          },
        },
        "required": [
          "page",
        ],
      },
      "outputSchema": null,
    },
    "./sections/WhatsApp.tsx": {
      "inputSchema": {
        "title": " Whats App",
        "type": "object",
        "properties": {
          "phone": {
            "type": [
              "number",
              "null",
            ],
            "title": "Phone",
          },
        },
        "required": [],
      },
      "outputSchema": null,
    },
    "./functions/mzVtexLegacyProductDetailsPage.ts": {
      "inputSchema": {
        "type": "null",
        "title": "Mz Vtex Legacy Product Details Page",
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "78c64adae4b16df19c6019918cf3380bc0a3ea85",
          },
        },
        "additionalProperties": true,
      },
    },
    "./functions/mzVtexLegacyProductList.ts": {
      "inputSchema": {
        "title": "Mz Vtex Legacy Product List",
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "title": "Query",
            "description": "query to use on search",
          },
          "count": {
            "type": "number",
            "title": "Count",
            "description": "total number of items to display",
          },
          "sort": {
            "type": "string",
            "anyOf": [
              {
                "type": "string",
                "const": "",
              },
              {
                "type": "string",
                "const": "price:desc",
              },
              {
                "type": "string",
                "const": "price:asc",
              },
              {
                "type": "string",
                "const": "orders:desc",
              },
              {
                "type": "string",
                "const": "name:desc",
              },
              {
                "type": "string",
                "const": "name:asc",
              },
              {
                "type": "string",
                "const": "release:desc",
              },
              {
                "type": "string",
                "const": "discount:desc",
              },
            ],
            "title": "Sort",
            "description": "search sort parameter",
          },
          "collection": {
            "type": "array",
            "items": {
              "type": "string",
            },
            "title": "Collection",
            "description":
              "Collection ID or (Product Cluster id). For more info: https://developers.vtex.com/docs/api-reference/search-api#get-/api/catalog_system/pub/products/search .",
            "pattern": "\\d*",
          },
        },
        "required": [
          "query",
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "21e924ba7ad9b59dcefae01b9b38a3fb983875f0",
          },
        },
        "additionalProperties": true,
      },
    },
    "./functions/mzVtexLegacyProductListingPage.ts": {
      "inputSchema": {
        "title": "Mz Vtex Legacy Product Listing Page",
        "type": "object",
        "properties": {
          "term": {
            "type": [
              "string",
              "null",
            ],
            "title": "Term",
            "description": "overides the query term",
          },
          "count": {
            "type": "number",
            "title": "Items per page",
            "description": "number of products per page to display",
          },
          "ft": {
            "type": [
              "string",
              "null",
            ],
            "title": "Ft",
            "description": "FullText term",
          },
          "fq": {
            "type": [
              "string",
              "null",
            ],
            "title": "Fq",
          },
          "map": {
            "type": [
              "string",
              "null",
            ],
            "title": "Map",
            "description": "map param",
          },
        },
        "required": [
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "9ba29fcac079080c6f7cf16f40f91cf15a25d53f",
          },
        },
        "additionalProperties": true,
      },
    },
    "$live/functions/EffectSelectPage.ts": {
      "inputSchema": {
        "title": " Effect Select Page",
        "type": "object",
        "properties": {
          "pageIds": {
            "type": "array",
            "items": {
              "type": "number",
            },
            "title": "Page Ids",
          },
        },
        "required": [
          "pageIds",
        ],
      },
      "outputSchema": null,
    },
    "$live/functions/MatchDate.ts": {
      "inputSchema": {
        "title": " Match Date",
        "type": "object",
        "properties": {
          "start": {
            "type": [
              "string",
              "null",
            ],
            "title": "Start",
            "format": "date-time",
          },
          "end": {
            "type": [
              "string",
              "null",
            ],
            "title": "End",
            "format": "date-time",
          },
          "session": {
            "type": "boolean",
            "title": "Session",
          },
        },
        "required": [
          "session",
        ],
      },
      "outputSchema": null,
    },
    "$live/functions/MatchEnvironment.ts": {
      "inputSchema": {
        "title": " Match Environment",
        "type": "object",
        "properties": {
          "environment": {
            "type": "string",
            "anyOf": [
              {
                "type": "string",
                "const": "production",
              },
              {
                "type": "string",
                "const": "development",
              },
            ],
            "title": "Environment",
          },
        },
        "required": [
          "environment",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "c995d72dc372b1b50bf9f70943e37fc94e1ccac9",
          },
        },
        "additionalProperties": true,
      },
    },
    "$live/functions/MatchRandom.ts": {
      "inputSchema": {
        "title": " Match Random",
        "type": "object",
        "properties": {
          "traffic": {
            "type": "number",
            "title": "Traffic",
          },
          "session": {
            "type": "boolean",
            "title": "Session",
          },
        },
        "required": [
          "traffic",
          "session",
        ],
      },
      "outputSchema": null,
    },
    "$live/functions/MatchSite.ts": {
      "inputSchema": {
        "title": " Match Site",
        "type": "object",
        "properties": {
          "siteId": {
            "type": "number",
            "title": "Site Id",
          },
        },
        "required": [
          "siteId",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "c995d72dc372b1b50bf9f70943e37fc94e1ccac9",
          },
        },
        "additionalProperties": true,
      },
    },
    "$live/functions/MatchUserAgent.ts": {
      "inputSchema": {
        "title": " Match User Agent",
        "type": "object",
        "properties": {
          "includes": {
            "type": [
              "string",
              "null",
            ],
            "title": "Includes",
          },
          "match": {
            "type": [
              "string",
              "null",
            ],
            "title": "Match",
          },
        },
        "required": [],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "c995d72dc372b1b50bf9f70943e37fc94e1ccac9",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/sections/SEO.tsx": {
      "inputSchema": {
        "title": " S E O",
        "type": "object",
        "properties": {
          "title": {
            "type": [
              "string",
              "null",
            ],
            "title": "Title",
          },
          "description": {
            "type": [
              "string",
              "null",
            ],
            "title": "Description",
          },
          "url": {
            "type": [
              "string",
              "null",
            ],
            "title": "Url",
          },
          "imageUrl": {
            "type": [
              "string",
              "null",
            ],
            "title": "Image Url",
          },
          "themeColor": {
            "type": [
              "string",
              "null",
            ],
            "title": "Theme Color",
          },
        },
        "required": [],
      },
      "outputSchema": null,
    },
    "deco-sites/std/sections/SEOPDP.tsx": {
      "inputSchema": {
        "title": " S E O P D P",
        "type": "object",
        "properties": {
          "page": {
            "$id": "78c64adae4b16df19c6019918cf3380bc0a3ea85",
            "format": "live-function",
            "type": "string",
            "title": "Page",
          },
          "titleTemplate": {
            "type": "string",
            "title": "Title template",
            "description":
              "add a %s whenever you want it to be replaced with the product name",
            "default": "%s | Fashion Store",
          },
          "description": {
            "type": [
              "string",
              "null",
            ],
            "title": "Meta tag description",
            "description":
              "If not set, the product description will be used instead",
          },
          "themeColor": {
            "type": [
              "string",
              "null",
            ],
            "title": "Theme Color",
          },
        },
        "required": [
          "page",
          "titleTemplate",
        ],
      },
      "outputSchema": null,
    },
    "deco-sites/std/sections/SEOPLP.tsx": {
      "inputSchema": {
        "title": " S E O P L P",
        "type": "object",
        "properties": {
          "page": {
            "$id": "05ecb684cf4ee00e98171fdc45227df637e4804e",
            "format": "live-function",
            "type": "string",
            "title": "Page",
          },
          "title": {
            "type": [
              "string",
              "null",
            ],
            "title": "Title",
          },
          "description": {
            "type": [
              "string",
              "null",
            ],
            "title": "Description",
          },
          "url": {
            "type": [
              "string",
              "null",
            ],
            "title": "Url",
          },
          "imageUrl": {
            "type": [
              "string",
              "null",
            ],
            "title": "Image Url",
          },
          "themeColor": {
            "type": [
              "string",
              "null",
            ],
            "title": "Theme Color",
          },
        },
        "required": [
          "page",
        ],
      },
      "outputSchema": null,
    },
    "deco-sites/std/sections/configOCC.global.tsx": {
      "inputSchema": {
        "title": "Config O C C.global",
        "type": "object",
        "properties": {
          "baseUrl": {
            "type": "string",
            "title": "Base Url",
          },
          "nrpp": {
            "type": [
              "string",
              "null",
            ],
            "title": "Nrpp",
          },
        },
        "required": [
          "baseUrl",
        ],
      },
      "outputSchema": null,
    },
    "deco-sites/std/sections/configShopify.global.tsx": {
      "inputSchema": {
        "title": "Config Shopify.global",
        "type": "object",
        "properties": {
          "storeName": {
            "type": "string",
            "title": "Store Name",
            "description": "Shopify store name.",
          },
          "storefrontAccessToken": {
            "type": "string",
            "title": "Storefront Access Token",
            "description": "Shopify storefront access token.",
          },
        },
        "required": [
          "storeName",
          "storefrontAccessToken",
        ],
      },
      "outputSchema": null,
    },
    "deco-sites/std/sections/configVTEX.global.tsx": {
      "inputSchema": {
        "title": "Config V T E X.global",
        "type": "object",
        "properties": {
          "account": {
            "type": "string",
            "title": "Account",
            "description":
              "VTEX Account name. For more info, read here: https://help.vtex.com/en/tutorial/o-que-e-account-name--i0mIGLcg3QyEy8OCicEoC.",
          },
          "defaultLocale": {
            "type": "string",
            "title": "Default Locale",
            "description": "Locale used for VTEX Intelligent Search client.",
          },
          "defaultPriceCurrency": {
            "type": "string",
            "title": "Default Price Currency",
            "description": "Default price currency.",
            "default": "USD",
          },
          "defaultSalesChannel": {
            "type": "string",
            "title": "Default Sales Channel",
            "description":
              "VTEX sales channel. This will be the default sales channel your site. For more info, read here: https://help.vtex.com/tutorial/how-trade-policies-work--6Xef8PZiFm40kg2STrMkMV",
          },
          "defaultRegionId": {
            "type": [
              "string",
              "null",
            ],
            "title": "Default Region Id",
          },
          "defaultHideUnnavailableItems": {
            "type": [
              "boolean",
              "null",
            ],
            "title": "Default Hide Unnavailable Items",
          },
        },
        "required": [
          "account",
          "defaultLocale",
          "defaultPriceCurrency",
          "defaultSalesChannel",
        ],
      },
      "outputSchema": null,
    },
    "deco-sites/std/functions/occProductDetailsPage.ts": {
      "inputSchema": {
        "type": "null",
        "title": "Occ Product Details Page",
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "78c64adae4b16df19c6019918cf3380bc0a3ea85",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/shopifyProductDetailsPage.ts": {
      "inputSchema": {
        "type": "null",
        "title": "Shopify Product Details Page",
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "78c64adae4b16df19c6019918cf3380bc0a3ea85",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/shopifyProductList.ts": {
      "inputSchema": {
        "title": "Shopify Product List",
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "title": "Query",
            "description": "search term to use on search",
          },
          "count": {
            "type": "number",
            "title": "Count",
            "description": "total number of items to display",
          },
        },
        "required": [
          "query",
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "1f15a836acd2ecbefef6eaf34ebcff98e39811f3",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/shopifyProductListingPage.ts": {
      "inputSchema": {
        "title": "Shopify Product Listing Page",
        "type": "object",
        "properties": {
          "query": {
            "type": [
              "string",
              "null",
            ],
            "title": "Query",
            "description": "overides the query term",
          },
          "count": {
            "type": "number",
            "title": "Items per page",
            "description": "number of products per page to display",
          },
        },
        "required": [
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "9ba29fcac079080c6f7cf16f40f91cf15a25d53f",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexConfig.ts": {
      "inputSchema": {
        "type": "null",
        "title": "Vtex Config",
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "4a94f4ff0e8e4441f26651aaed22f0df82f38c93",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexLegacyProductDetailsPage.ts": {
      "inputSchema": {
        "type": "null",
        "title": "Vtex Legacy Product Details Page",
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "78c64adae4b16df19c6019918cf3380bc0a3ea85",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexLegacyProductList.ts": {
      "inputSchema": {
        "title": "Vtex Legacy Product List",
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "title": "Query",
            "description": "query to use on search",
          },
          "count": {
            "type": "number",
            "title": "Count",
            "description": "total number of items to display",
          },
          "sort": {
            "type": "string",
            "anyOf": [
              {
                "type": "string",
                "const": "",
              },
              {
                "type": "string",
                "const": "price:desc",
              },
              {
                "type": "string",
                "const": "price:asc",
              },
              {
                "type": "string",
                "const": "orders:desc",
              },
              {
                "type": "string",
                "const": "name:desc",
              },
              {
                "type": "string",
                "const": "name:asc",
              },
              {
                "type": "string",
                "const": "release:desc",
              },
              {
                "type": "string",
                "const": "discount:desc",
              },
            ],
            "title": "Sort",
            "description": "search sort parameter",
          },
          "collection": {
            "type": "array",
            "items": {
              "type": "string",
            },
            "title": "Collection",
            "description":
              "Collection ID or (Product Cluster id). For more info: https://developers.vtex.com/docs/api-reference/search-api#get-/api/catalog_system/pub/products/search .",
            "pattern": "\\d*",
          },
        },
        "required": [
          "query",
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "1f15a836acd2ecbefef6eaf34ebcff98e39811f3",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexLegacyProductListingPage.ts": {
      "inputSchema": {
        "title": "Vtex Legacy Product Listing Page",
        "type": "object",
        "properties": {
          "term": {
            "type": [
              "string",
              "null",
            ],
            "title": "Term",
            "description": "overides the query term",
          },
          "count": {
            "type": "number",
            "title": "Items per page",
            "description": "number of products per page to display",
          },
          "ft": {
            "type": [
              "string",
              "null",
            ],
            "title": "Ft",
            "description": "FullText term",
          },
          "fq": {
            "type": [
              "string",
              "null",
            ],
            "title": "Fq",
          },
          "map": {
            "type": [
              "string",
              "null",
            ],
            "title": "Map",
            "description": "map param",
          },
        },
        "required": [
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "9ba29fcac079080c6f7cf16f40f91cf15a25d53f",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexProductDetailsPage.ts": {
      "inputSchema": {
        "type": "null",
        "title": "Vtex Product Details Page",
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "78c64adae4b16df19c6019918cf3380bc0a3ea85",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexProductList.ts": {
      "inputSchema": {
        "title": "Vtex Product List",
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "title": "Query",
            "description": "query to use on search",
          },
          "count": {
            "type": "number",
            "title": "Count",
            "description": "total number of items to display",
          },
          "sort": {
            "type": "string",
            "anyOf": [
              {
                "type": "string",
                "const": "",
              },
              {
                "type": "string",
                "const": "price:desc",
              },
              {
                "type": "string",
                "const": "price:asc",
              },
              {
                "type": "string",
                "const": "orders:desc",
              },
              {
                "type": "string",
                "const": "name:desc",
              },
              {
                "type": "string",
                "const": "name:asc",
              },
              {
                "type": "string",
                "const": "release:desc",
              },
              {
                "type": "string",
                "const": "discount:desc",
              },
            ],
            "title": "Sort",
            "description": "search sort parameter",
          },
          "collection": {
            "type": "array",
            "items": {
              "type": "string",
            },
            "title": "Collection",
            "description":
              "Collection ID or (Product Cluster id). For more info: https://developers.vtex.com/docs/api-reference/search-api#get-/api/catalog_system/pub/products/search .",
            "pattern": "\\d*",
          },
        },
        "required": [
          "query",
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "1f15a836acd2ecbefef6eaf34ebcff98e39811f3",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexProductListingPage.ts": {
      "inputSchema": {
        "title": "Vtex Product Listing Page",
        "type": "object",
        "properties": {
          "query": {
            "type": [
              "string",
              "null",
            ],
            "title": "Query",
            "description": "overides the query term",
          },
          "count": {
            "type": "number",
            "title": "Items per page",
            "description": "number of products per page to display",
          },
        },
        "required": [
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "9ba29fcac079080c6f7cf16f40f91cf15a25d53f",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexSuggestions.ts": {
      "inputSchema": {
        "title": "Vtex Suggestions",
        "type": "object",
        "properties": {
          "count": {
            "type": [
              "number",
              "null",
            ],
            "title": "Count",
            "description": "limit the number of searches",
            "default": "4",
          },
        },
        "required": [],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "664f9b3b60b4a75294c340d8218b4ad76821fd58",
          },
        },
        "additionalProperties": true,
      },
    },
  },
  baseUrl: import.meta.url,
  config,
};

// live — this exposes the manifest so the live server can render components dynamically
context.manifest = manifest;

export default manifest;
